export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const POSTS_ACTION_START = "POSTS_ACTION_START";
export const POSTS_ACTION_SUCCESS = "POSTS_ACTION_SUCCESS";
export const POSTS_ACTION_FAIL = "POSTS_ACTION_FAIL";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";

export const PROFILES_ACTION_START = "PROFILES_ACTION_START";
export const PROFILES_ACTION_SUCCESS = "PROFILES_ACTION_SUCCESS";
export const PROFILES_ACTION_FAIL = "PROFILES_ACTION_FAIL";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
